import AsyncStorage from "@react-native-async-storage/async-storage";
import { create } from "zustand";
import { createJSONStorage, persist } from "zustand/middleware";
import type { Product, ProductCategory } from "@/types/product";

interface ProductState {
	products: Product[];
	categories: ProductCategory[];
	searchQuery: string;
	selectedCategory: ProductCategory | null;
	setSearchQuery: (query: string) => void;
	setSelectedCategory: (category: ProductCategory | null) => void;
}

const allCategories: ProductCategory[] = [
	"Groceries",
	"Beverages",
	"Dairy",
	"Snacks",
	"Household",
	"Personal Care",
];

const initialProducts: Product[] = [
	{
		id: "1",
		name: "White Sugar (1kg)",
		price: 180,
		description:
			"Pure refined white sugar, perfect for everyday cooking and baking.",
		category: "Groceries",
		image: "🍬",
		rating: 4.5,
		inStock: true,
	},
	{
		id: "2",
		name: "Bread (White Loaf)",
		price: 65,
		description: "Fresh white bread, soft and delicious. Baked daily.",
		category: "Groceries",
		image: "🍞",
		rating: 4.8,
		inStock: true,
	},
	{
		id: "3",
		name: "Fresh Milk (500ml)",
		price: 70,
		description: "Farm-fresh pasteurized whole milk. Rich in calcium.",
		category: "Dairy",
		image: "🥛",
		rating: 4.6,
		inStock: true,
	},
	{
		id: "4",
		name: "Cooking Oil (1L)",
		price: 350,
		description: "Premium vegetable cooking oil. Heart-healthy choice.",
		category: "Groceries",
		image: "🫒",
		rating: 4.3,
		inStock: true,
	},
	{
		id: "5",
		name: "Soda (500ml)",
		price: 60,
		description: "Refreshing carbonated soft drink. Serve chilled.",
		category: "Beverages",
		image: "🥤",
		rating: 4.2,
		inStock: true,
	},
	{
		id: "6",
		name: "Rice (2kg)",
		price: 280,
		description: "Premium long-grain white rice. Fluffy and aromatic.",
		category: "Groceries",
		image: "🍚",
		rating: 4.7,
		inStock: true,
	},
	{
		id: "7",
		name: "Eggs (Tray of 30)",
		price: 480,
		description: "Farm-fresh eggs. Rich in protein. Free-range.",
		category: "Dairy",
		image: "🥚",
		rating: 4.9,
		inStock: true,
	},
	{
		id: "8",
		name: "Washing Soap (Bar)",
		price: 45,
		description: "Multi-purpose laundry bar soap. Tough on stains.",
		category: "Household",
		image: "🧼",
		rating: 4.1,
		inStock: true,
	},
	{
		id: "9",
		name: "Tea Leaves (250g)",
		price: 220,
		description: "Kenyan premium black tea. Rich flavor and aroma.",
		category: "Beverages",
		image: "🍵",
		rating: 4.8,
		inStock: true,
	},
	{
		id: "10",
		name: "Butter (250g)",
		price: 320,
		description: "Creamy salted butter. Perfect for toast and cooking.",
		category: "Dairy",
		image: "🧈",
		rating: 4.5,
		inStock: true,
	},
	{
		id: "11",
		name: "Toothpaste (100ml)",
		price: 150,
		description: "Fluoride toothpaste for complete dental protection.",
		category: "Personal Care",
		image: "🪥",
		rating: 4.4,
		inStock: true,
	},
	{
		id: "12",
		name: "Biscuits (Family Pack)",
		price: 50,
		description: "Crunchy biscuits, perfect for tea time.",
		category: "Snacks",
		image: "🍪",
		rating: 4.3,
		inStock: true,
	},
	{
		id: "13",
		name: "Juice (1L)",
		price: 180,
		description: "Natural fruit juice blend. No added sugar.",
		category: "Beverages",
		image: "🧃",
		rating: 4.6,
		inStock: true,
	},
	{
		id: "14",
		name: "Yoghurt (500ml)",
		price: 120,
		description: "Creamy vanilla yoghurt. Probiotic cultures.",
		category: "Dairy",
		image: "🥣",
		rating: 4.7,
		inStock: true,
	},
	{
		id: "15",
		name: "Chips (Large)",
		price: 80,
		description: "Crispy salted potato chips. Great snack.",
		category: "Snacks",
		image: "🥔",
		rating: 4.0,
		inStock: true,
	},
	{
		id: "16",
		name: "Dish Soap (500ml)",
		price: 95,
		description: "Concentrated dish washing liquid. Cuts grease.",
		category: "Household",
		image: "🫧",
		rating: 4.2,
		inStock: true,
	},
	{
		id: "17",
		name: "Coffee (100g)",
		price: 450,
		description: "Kenyan AA premium ground coffee. Bold flavor.",
		category: "Beverages",
		image: "☕",
		rating: 4.9,
		inStock: true,
	},
	{
		id: "18",
		name: "Body Lotion (200ml)",
		price: 250,
		description: "Moisturizing body lotion. All-day hydration.",
		category: "Personal Care",
		image: "🧴",
		rating: 4.3,
		inStock: true,
	},
	{
		id: "19",
		name: "Maize Flour (2kg)",
		price: 160,
		description: "Fine maize flour for ugali and baking.",
		category: "Groceries",
		image: "🌽",
		rating: 4.6,
		inStock: true,
	},
	{
		id: "20",
		name: "Chocolate Bar",
		price: 100,
		description: "Smooth milk chocolate. Premium cocoa.",
		category: "Snacks",
		image: "🍫",
		rating: 4.8,
		inStock: true,
	},
];

export const useProductStore = create<ProductState>()(
	persist(
		(set) => ({
			products: initialProducts,
			categories: allCategories,
			searchQuery: "",
			selectedCategory: null,
			setSearchQuery: (query) => set({ searchQuery: query }),
			setSelectedCategory: (category) => set({ selectedCategory: category }),
		}),
		{
			name: "bizross-customer-products",
			storage: createJSONStorage(() => AsyncStorage),
		},
	),
);
